name: SleiyiPluglin
version: '1.0'
main: me.theweebcrafter.sleiyiPluglin.SleiyiPluglin
api-version: '1.20'
authors: [TheWeebCrafter]
description: Pluglin de sleyi
website: https://www.youtube.com/@TheWeebCrafter
